-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2021-01-11 02:49:53 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g


/*
DROP SYNONYM atr_rodzaju_umowy;
DROP SYNONYM def_atrybutu;
DROP SYNONYM rodz_umowy;
DROP SYNONYM umowa_cywpraw;
DROP SYNONYM wart_atrybutu;
DROP SYNONYM wykon;
*/

DROP SYNONYM atrybut_rodzaju_umowy;
DROP SYNONYM definicja_atrybutu;
DROP SYNONYM rodzaj_umowy;
DROP SYNONYM umowa_cywilnoprawna;
DROP SYNONYM wartosc_atrybutu;
DROP SYNONYM wykonawca;

CREATE OR REPLACE SYNONYM atrybut_rodzaju_umowy FOR BD2A31.atrybut_rodzaju_umowy;

CREATE OR REPLACE SYNONYM definicja_atrybutu FOR BD2A31.definicja_atrybutu;

CREATE OR REPLACE SYNONYM rodzaj_umowy FOR BD2A31.rodzaj_umowy;

CREATE OR REPLACE SYNONYM umowa_cywilnoprawna FOR BD2A31.umowa_cywilnoprawna;

CREATE OR REPLACE SYNONYM wartosc_atrybutu FOR BD2A31.wartosc_atrybutu;

CREATE OR REPLACE SYNONYM wykonawca FOR BD2A31.wykonawca;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             0
-- CREATE INDEX                             0
-- ALTER TABLE                              0
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           6
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
